
GRANT CONTROL ON TABLE "HKYH"."T_DIY_YQXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "HKYH"."T_DIY_YQXX" TO USER "HKYH" ;

GRANT CONTROL ON TABLE "HKYH"."T_KP_XYKZKM" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "HKYH"."T_KP_XYKZKM" TO USER "HKYH" ;
